data:
  - "data/blocks/replay_buffer.zarr"
task:
  - "Stack the blocks in order."
features:
  left_wrist_img:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  state:
    dtype: "float32"
    shape: [7,] 
    names: ["state"]
  actions:
    dtype: "float32"
    shape: [7,]
    names: ["actions"]