data:
  /mnt/model/1010_pick_two_boxes_am:
      num_episodes: 109
      lines: null
      invalid_id: [26, 33, 35, 47, 53, 58, 63, 66, 71, 80, 96, 5,9,14,18,23,26,27,35,36,43,73,74,75,101]
      feat: 
        img_left: OpenCVCameraDevice_0
        img_right: OpenCVCameraDevice_2
        pose_unified: ViveTrackerDevice_0 
        grip_left: RotaryEncoderDevice_0
        grip_right: RotaryEncoderDevice_1
      masks:
        mask_left: ../mask/left_umi_mask.png
        mask_right: ../mask/right_umi_mask.png

  # additional failed episodes 30,43,91
  /mnt/model/1010_pick_two_boxes_pm:
      num_episodes: 120
      lines: null
      invalid_id: [1, 10, 13, 22, 23, 24, 27, 29, 30, 31, 38, 43, 44, 48, 50, 51, 53, 56, 61, 64, 65, 66, 70, 76, 78, 82, 84, 89, 90, 91, 97, 104,6,14,17,31,50,51,61,62,63,76,77,78,86,93,111]
      feat: 
        img_left: OpenCVCameraDevice_0
        img_right: OpenCVCameraDevice_2
        pose_unified: ViveTrackerDevice_0 
        grip_left: RotaryEncoderDevice_0
        grip_right: RotaryEncoderDevice_1
      masks:
        mask_left: ../mask/left_umi_mask.png
        mask_right: ../mask/right_umi_mask.png

features:
  left_wrist_image:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  right_wrist_image: 
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  state:
    dtype: "float32"
    shape: [14,] 
    names: ["state"]
  actions:
    dtype: "float32"
    shape: [14,]
    names: ["actions"]