data:
  - "/mnt/model/Codes/openpi/1016_merged_data.zarr.zip"
task:
  - "place the wooden block and the blue block in the dark area"
features:
  left_wrist_image:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  right_wrist_image: 
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  state:
    dtype: "float32"
    shape: [14,] 
    names: ["state"]
  actions:
    dtype: "float32"
    shape: [14,]
    names: ["actions"]