data:
  /mnt/model/0925_pick_two_dolls_v6:
    task: pick the two dolls from the table to the dark area
    num_episodes: 133
    lines: null
    invalid_id: [1, 4, 6, 10, 13, 22, 23, 24, 47, 69, 76, 82, 88, 92, 94, 99, 101, 104, 109, 125, 128, 111, 113, 114, 118, 126, 127, 131]
    feat: 
      img_left: OpenCVCameraDevice_1
      img_right: OpenCVCameraDevice_6
      pose_unified: ViveTrackerDevice_0 
      grip_left: RotaryEncoderDevice_0
      grip_right: RotaryEncoderDevice_1
    masks:
      mask_left: ../mask/left_umi_mask.png
      mask_right: ../mask/right_umi_mask.png

features:
  left_wrist_image:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  right_wrist_image: 
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  state:
    dtype: "float32"
    shape: [14,] 
    names: ["state"]
  actions:
    dtype: "float32"
    shape: [14,]
    names: ["actions"]
  
