data:
  - "data/pourmsg/replay_buffer.zarr"
task:
  - "Pick up three seasoning jars, sprinkle the seasonings, and then place the jars back down."
features:
  left_wrist_img:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  state:
    dtype: "float32"
    shape: [7,] 
    names: ["state"]
  actions:
    dtype: "float32"
    shape: [7,]
    names: ["actions"]