data:
  - "/mnt/data/shenyibo/workspace/umi_base/.cache/q3_mouse_dh_train/replay_buffer.zarr"
task:
  - "Pick up the mouse and place it on the black mouse pad"
features:
  left_wrist_img:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  left_eye_img:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  right_eye_img:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  state:
    dtype: "float32"
    shape: [6,] 
    names: ["state"]
  actions:
    dtype: "float32"
    shape: [7,]
    names: ["actions"]