data:
  - "/mnt/model/dsl_data/umi_1010all_server/dataset.zarr.zip"
task:
  - "pick the green box and the blue box to the dark area"
features:
  left_wrist_image:
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  right_wrist_image: 
    dtype: "image"
    shape: [224, 224, 3]
    names: ["height", "width", "channel"]
  state:
    dtype: "float32"
    shape: [14,] 
    names: ["state"]
  actions:
    dtype: "float32"
    shape: [14,]
    names: ["actions"]
  prev_state:
    dtype: "float32"
    shape: [14,] 
    names: ["prev_state"]